Added datasets in docs
PyTorchLightning/lightning-bolts pull request #752
Opened 2021-10-16 19:13 UTC by Programmer-RD-AI

## What does this PR do?

Added datasets in docs

https://pytorch-lightning-bolts.readthedocs.io/en/latest/datasets.html
https://github.com/Programmer-RD-AI/lightning-bolts/tree/master/pl_bolts/datasets

Fixes #339 (issue)

## Before submitting

- [x] Was this **discussed/approved** via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/lightning-bolts/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does **only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes?
- [x] Did you write any **new necessary tests**? \[not needed for typos/docs\]
- [x] Did you verify new and **existing tests** pass locally with your changes?
- [x] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/lightning-bolts/blob/master/CHANGELOG.md)?

## PR review

- [x] Is this pull request **ready for review**? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?

Yes, I had a lot of fun and I learned a lot of new stuff with contributing I am new to contributing so I am learning and super interested.

@Borda does this add all of the docs needed? 

With best regards,
Ranuga

2021-11-08 16:59 UTC, Borda approved these changes

2021-11-18 21:31 UTC, Borda requested changes
pls, why are you removing all these images from docs?

2021-12-20 11:34 UTC, Borda commented
@Programmer-RD-AI seems that your added API references are not working, mind checking it?
you can debug it locally with `make docs`

2021-12-20 12:34 UTC, Programmer-RD-AI commented
hi, I am so sorry But I have a lot of work to do so I won't be able to work in this PR.
Again I am sorry.

2021-12-20 17:47 UTC, closed without merging